eureka:
  client:
    serviceUrl:
      defaultZone: https://user:user@hxline-registry.herokuapp.com:http://user:password@localhost:5000/eureka/
security:
  user:
    password: ${eureka.password}

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: localhost
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}